### ISSUE TITLE
Possible Memory Leak in Linux

### ISSUE THREAD

**Issue by tank-trax** [ODDSound/MTS-ESP#11]
Operating System: Debian GNU/Linux 11
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-15-rt-amd64
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3470 CPU @ 3.20GHz
Memory: 11.4 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 2500

I am seeing a bug in Entonal Studio when MTS-ESP is enabled

if I have 4 synths attached and close the session and reopen it will say there are 5 Connected clients when the session is reopened
close it and open it again and it becomes 6, again and it's 7

if Entonal Studio is opened in another DAW it will already say that 3 clients are connected 

logging of and on does not resolve it
rebooting does
I also found that over-writing libMTS.so in /etc/local/lib also resets it

if Entonal Studio crashes in Bitwig and is re-enabled there will appear this message

![image](https://user-images.githubusercontent.com/41337033/173267263-6f9bc48d-4a4a-419b-aa4d-30573a775f9b.png)

Clicking OK will set the clients to zero, closing and re-opening the session will set things back to how they should be, however each subsequent closing and opening of  Entonal Studio will show its MTS-ESP function as having added a new client

each time a session is closed that has Entonal Master on a track and new one is opened in any DAW, the same or another, it's as if a new client is added, it appears that

a) Entonal Master appears to also register itself as a client, not on the initial session but on each subsequent one and it increments with each new session
b) it doesn't appear to stop running or it counts as a client after a session is closed (possible memory leak)
c) rebooting, crashing Entonal Studio or overwriting libMTS.so resets the clock

**Comment by olicash** [comment]
A plug-in must register itself with the MTS-ESP library on construction **and** deregister itself on destruction.  It can register as either as a client, master, or even both if you like.  As you suggest, I think there is some mis-matched registering/de-registering going on, worth reporting to Entonal.  

MTS-ESP uses shared memory for IPC, for hosts like Bitwig that support plug-in sandboxing.  When the library is first loaded the shared memory is created.  The shared memory persists until all IPC clients have deregistered and unloaded the library.  If a plug-in doesn't deregister, or there is a crash, the shared memory will persist.  If the process in which the master is running crashes, the master won't deregister itself, the flag in MTS-ESP that stores whether a master is instanced will remain set and MTS_CanRegisterMaster() will return false when a new instance is created.  This is why you are seeing the error message from Entonal.  "Reinitialize" means the data in the MTS-ESP shared memory is reset, including the client count, so that a master can attempt to register again.  This is why you see the client count set to zero and why subsequently closing and reopening a DAW session corrects it.  If you are getting a lot of crashes or doing dev work and terminating processes often, it can be useful to disable IPC so you don't see that message, although of course you'll need to make sure all MTS-ESP plug-ins are running in the same process. 

For more see "IPC Support" on p.12 of the MTS-ESP Master manual (https://oddsound.com/dl/ODDSound_MTS_ESP_Suite_Master_Manual.pdf), the comments in libMTSMaster.h (https://github.com/ODDSound/MTS-ESP/blob/main/Master/libMTSMaster.h) and the readme in this repo.

**Comment by tank-trax** [comment]
if I may add, I would suggest to have IPC disabled by default 
and if enabled would it be possible to create a mechanism to reset it or manage IPC connections?

**Comment by olicash** [comment]
The principal reason for having IPC enabled by default is Apple's transition from Intel to ARM.  On an ARM Mac it may still be quite possible that Intel and ARM plug-in binaries are running in separate processes.  Other reasons are that MTS-ESP will work in other situations where plug-ins are running in separate processes (Bitwig, FL Studio, Reaper and Waveform can all do this) and that it's quite nice for it to work across multiple applications, e.g. I have used Bitwig and VCVRack together running as separate applications in the past.  Of course it can be up to the developer of a master plug-in whether IPC is enabled or disabled by default, as their installer should include the MTS-ESP shared library and, optionally the accompanying conf file which can be set as desired, so long as it doesn't overwrite one that already exists.  For us, having it enabled means less emails to support, and if anyone ever does ask we have a video explaining it here: https://youtu.be/x95vSbTOXOc.

We have included a mechanism to reset the MTS-ESP library with the MTS_Reinitialize() call that I alluded to in my last comment.  This resets everything in the MTS-ESP library to its default state...the tuning (to 12-TET), note filters, client count, scale name and multichannel state.  This should only ever be called if IPC is enabled and only by a master plug-in, hence it being in the master API.  As documented in libMTSMaster.h, the correct thing for a master to do on construction is:

`if (MTS_CanRegisterMaster())
	MTS_RegisterMaster();
else {
	if (MTS_HasIPC()) {
		Warn user another master is already connected, but give them an option to re-initialize MTS-ESP in case there was a crash and no master is connected any more;
		If (user clicks to re-initialize MTS-ESP) {
			MTS_Reinitialize();
			MTS_RegisterMaster();
		}
	}
	else
		Warn user another master is already connected, do not give them an option to re-initialize MTS-ESP;
}`

This is what Entonal does, hence seeing the error message in your screenshot.  It is what our master plug-ins do too.

Managing IPC connections is implicitly done through the lifetime of processes that load the MTS-ESP shared library.

If I'm barking up the wrong tree here, perhaps some concrete examples of situations or things you are trying to achieve could help?

**Comment by tank-trax** [comment]
Here is an example of the behaviour where with each session a new client is added

In Bitwig with a clean slate there are 4 clients. Closing the session and reopening and now there are 5. Close reopen and it's 6.

Now we are at 2+ghost clients. Opening another will put it at 3+. The next Reaper session has 2 actual clients +3 and it states 5. Again and again it's 7. That's +5 if I was to open the Bitwig session with 4 actual clients it would say 13 clients now.

Apparently this behaviour happens in OSX and @baconpaul thinks it is libMTS.so at issue. I would have to agree as if I overwrite the library it resets everything back to square 1.

https://user-images.githubusercontent.com/41337033/192069331-2a6124ec-10b0-47bc-b681-31a69662f895.mp4

**Comment by olicash** [comment]
Thanks for the vid, that makes things clear now.  Before going any further, there is some extra info I'd like to know, if possible...

- What are the two client plug-ins in the Reaper session you loaded?  I think one is Monique but I can't see what the other is in the vid.

- What happens if you try the exact same as in the video, but use multiple instances of the same client plug-in, instead of different client plug-ins.  I suggest Surge XT, try a Bitwig session with a single instance of Entonal, 4 instances of Surge XT and let me know if you still get the same behaviour.

Many thanks!

**Comment by olicash** [comment]
Oh, one further bit of info...what is the hosting mode set to in Bitwig's plug-in preferences?  Are all plug-ins running in the same process?  Or all different processes?  That would be most helpful to know.

**Comment by tank-trax** [comment]
apologies for the delay and thanks for your patience

> What are the two client plug-ins in the Reaper session you loaded? I think one is Monique but I can't see what the other is in the vid.

Entonal on Track1, Surge XT and Monique on 2 and 3

> What happens if you try the exact same as in the video, but use multiple instances of the same client plug-in, instead of different client plug-ins. I suggest Surge XT, try a Bitwig session with a single instance of Entonal, 4 instances of Surge XT and let me know if you still get the same behaviour.

Same thing

For Bitwig the setting did not matter if sanboxed Together or Individually

in all instances this behaviour occurs when `ipc_support = 1`

when `ipc_support = 0` the correct clients are listed, so it appears to be an issue with IPC, but I could be wrong

**Comment by tank-trax** [comment]
here's an update as there was a mistake in my last assumption, with IPC disabled for MTS-ESP master to work in Bitwig without adding clients the plugins need to be Hosted Together, any combination of Individually or By Plug/Dev won't list the clients if IPC is disabled, if enabled the stacking happens whether together or individually

However I noticed that the behaviour still happens when mts-esp master is enabled in Reaper 
each new session still adds a new client

**Comment by tank-trax** [comment]
IPC on Linux works. @baconpaul has been working on Surge XT as MTS Source and we encountered this issue however looks to be resolved... there was some misbehaving

hopefully this translates well

the fix had something to with not calling `MTS_REgisterMaster` if `MTS_CanRegisterMaster` returns false; and in surge we didn't get all the paths so it was put super close to the register call

The link him to this commit:

https://github.com/surge-synthesizer/surge/commit/8511acc0b78997afd484ae0df1ead388ccb49191

I can close this issue.

Thanks

**Comment by olicash** [comment]
Nice, glad this seems to be working as it had me scratching my head!  I have added some example pseudocode for registering to libMTSMaster.h which I think may help in future.

**Comment by baconpaul** [comment]
yeah crashing masters etc... really didn't help.

hey if you want I wrote https://github.com/baconpaul/mts-status a tiny little command line that tells you your IPC status and also lets you do a reset if canregistermaster is false. All yours if you want to take it and so on. 

but for surge-as-master once i blocked *all* paths to register in a can register it was fine; i wonder if entonal has a similar form of bug (our bug was a state unstream would not check but a user action would so if you saved as master and re-loaded it would be spannered)

**Comment by tank-trax** [comment]
as an aside I hope this encourages OddSound to build a Linux version of the MTS-ESP Suite and/or MTS-ESP Mini :-)
