### ISSUE TITLE
Including both Client and Master under one program

### ISSUE THREAD

**Issue by zardini123** [ODDSound/MTS-ESP#7]
Recently I've attempted to include both MTS-ESP Client and Master headers under one C++ program.  Upon compiling, the following warning emerges:

```
warning: conflicting C language linkage declaration MTS_HasMaster()
107 |     extern bool MTS_HasMaster();
```
and
```
note: previous declaration MTS_HasMaster(MTSClient*)
   85 |     extern bool MTS_HasMaster(MTSClient *client);
```

Is having both Client and Master under the same program intended by MTS-ESP developers?  I'd there would be use cases of a synthesizer plugin that can operate as both the Client and Master.  Is there a work around to include both headers without any warning?

**Comment by olicash** [comment]
My apologies, no function overloading in C!  I've fixed by changing the name of MTS_HasMaster() in the master API to MTS_CanRegisterMaster().  Don't call MTS_RegisterMaster() if this returns false.  Hopefully now you should be able to include both (seems you're the first to do so)!  Let me know if any further issues.  Cheers!  Oli.

**Comment by zardini123** [comment]
Awesome, works great now!  Thank you Oli!
